name: 開発版
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup nuget
        uses: nuget/setup-nuget@v1

      - name: msbuild setup
        uses: microsoft/setup-msbuild@v1.1

      - name: restore nuget
        shell: cmd
        run: |
          nuget restore Satolist2.sln

      - name: set version
        shell: cmd
        run: |
          echo namespace Satolist2 { public static class Version { public static string VersionString = "Satoist2 Development Version: #%GITHUB_RUN_NUMBER%"; public static long VersionIndex = %GITHUB_RUN_NUMBER%; } } > Satolist2\Version.cs

      - name: run msbuild
        shell: cmd
        run: |
          MSBuild.exe Satolist2.sln -property:Configuration=Deploy;Platform="Any CPU" -t:rebuild

      - name: make filelist
        shell: cmd
        run: |
          pushd Satolist2\bin\Deploy
          ..\..\..\UpdateFileListGenerator\bin\Deploy\UpdateFileListGenerator.exe data\files
          popd

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Satolist2-Dev
          path: Satolist2/bin/Deploy
