name: test-build
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup nuget
        uses: nuget/setup-nuget@v1

      - name: msbuild setup
        uses: microsoft/setup-msbuild@v1.1

      - name: restore nuget
        shell: cmd
        run: |
          nuget restore Satolist2.sln
      
      - name: run msbuild
        shell: cmd
        run: |
          MSBuild.exe Satolist2/Satolist2.csproj -property:Configuration=Deploy;Platform=AnyCPU

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: Satolist2/bin/Deploy
